CREATE TABLE `rebateCalculations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`firstName` varchar(255) NOT NULL,
	`lastName` varchar(255),
	`email` varchar(320),
	`phone` varchar(50),
	`address` varchar(500) NOT NULL,
	`city` varchar(255),
	`state` varchar(50),
	`zip` varchar(20),
	`propertyType` enum('single_family','multi_family','condo','townhouse') DEFAULT 'single_family',
	`squareFootage` int,
	`bedrooms` int,
	`bathrooms` int,
	`stories` int,
	`currentSystem` enum('gas_furnace','oil_furnace','electric_baseboard','central_ac','heat_pump','window_ac','none'),
	`systemAge` int,
	`psegRebateCents` int,
	`federalTaxCreditCents` int,
	`totalRebateCents` int,
	`selectedOption` enum('high_efficiency','standard'),
	`selectedPaymentTier` enum('full_finance','deposit_12pct','full_payment'),
	`projectCostCents` int,
	`outOfPocketCents` int,
	`assessmentRequested` boolean NOT NULL DEFAULT false,
	`assessmentStatus` enum('pending','scheduled','completed','cancelled') DEFAULT 'pending',
	`assessmentNotes` text,
	`propertyDataJson` text,
	`status` enum('new','contacted','scheduled','won','lost') DEFAULT 'new',
	`assignedTo` varchar(255),
	`internalNotes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `rebateCalculations_id` PRIMARY KEY(`id`)
);
