/**
 * Post-build static prerender.
 *
 * `vite build` produces dist/public/index.html with an empty <div id="root">
 * and one JS bundle — curl (and any crawler that doesn't execute JS) sees no
 * content. This script renders every URL already listed in sitemap.xml
 * (client/public/sitemap.xml, generated by scripts/generate-sitemap.ts as an
 * earlier build step) to a real static HTML file at
 * dist/public/{route}/index.html, with the actual page markup, title, meta
 * description, canonical, and JSON-LD already inlined — using
 * react-dom/server against the same App component tree the browser uses.
 * The client bundle then hydrates on top (see client/src/main.tsx).
 *
 * client/src/entry-server.tsx is loaded through Vite's `ssrLoadModule` (not
 * a plain Node import) so it gets the same env-var injection, `@`/`@shared`
 * alias resolution, and JSX transform the real client build gets — running
 * it as a bare Node/tsx import fails on `import.meta.env.VITE_*` (undefined
 * outside Vite's transform) used by a handful of components.
 *
 * Run: npx tsx scripts/prerender.ts   (after `vite build`, before the server bundle step)
 */
import fs from "fs";
import path from "path";
import { createServer, type ViteDevServer } from "vite";
import { injectMeta } from "../netlify/edge-functions/inject-meta";

// App.tsx statically imports every page component, including admin-only
// tools that are never in sitemap.xml and never rendered here (e.g. the
// take-off PDF viewer). Importing the module graph still evaluates their
// top-level code, and pdfjs-dist references a couple of browser-only globals
// at module scope. These are never actually called during a marketing-page
// render — the stubs just need to exist so the import doesn't crash.
for (const name of ["DOMMatrix", "Path2D", "ImageData"]) {
  if (!(name in globalThis)) {
    (globalThis as Record<string, unknown>)[name] = class {};
  }
}

// Shared components (Navigation's useAuth, a couple of page-level useState
// initializers) read/write localStorage/sessionStorage during render, not
// just in effects — real behavior for an anonymous, logged-out visitor, but
// it needs the API to exist under SSR. An in-memory stub is correct here:
// every prerendered page starts from a fresh, empty store (matching what a
// real anonymous browser session sees), and nothing written during a
// server render should carry over between routes or into the client.
class MemoryStorage implements Storage {
  private store = new Map<string, string>();
  get length() { return this.store.size; }
  clear() { this.store.clear(); }
  getItem(key: string) { return this.store.has(key) ? this.store.get(key)! : null; }
  key(index: number) { return Array.from(this.store.keys())[index] ?? null; }
  removeItem(key: string) { this.store.delete(key); }
  setItem(key: string, value: string) { this.store.set(key, String(value)); }
}
for (const name of ["localStorage", "sessionStorage"]) {
  if (!(name in globalThis)) {
    (globalThis as Record<string, unknown>)[name] = new MemoryStorage();
  }
}

const root = path.resolve(import.meta.dirname, "..");
const distDir = path.join(root, "dist", "public");
const shellPath = path.join(distDir, "index.html");

// Routes behind auth (admin/dashboard/etc.) are never in sitemap.xml —
// scripts/generate-sitemap.ts already excludes protect()-wrapped routes and
// utility paths — so "every URL in sitemap.xml" is exactly the public set.
function getRoutesFromSitemap(): string[] {
  const xml = fs.readFileSync(path.join(root, "client", "public", "sitemap.xml"), "utf-8");
  const locs = Array.from(xml.matchAll(/<loc>([^<]+)<\/loc>/g)).map((m) => m[1]);
  return locs.map((u) => new URL(u).pathname);
}

// Flat "{route}.html" — NOT "{route}/index.html". Netlify serves a bare
// extensionless path from name.html directly (its native pretty-URL
// convention); if only name/index.html exists, it 301s the bare path to
// name/ first. Since sitemap.xml, canonical tags, and every internal link
// use the no-trailing-slash form, a flat file avoids that extra redirect
// hop entirely — verified against the live deploy.
function outPathFor(routePath: string): string {
  if (routePath === "/") return path.join(distDir, "index.html");
  return path.join(distDir, `${routePath.replace(/^\//, "")}.html`);
}

async function main() {
  if (!fs.existsSync(shellPath)) {
    console.error(`[prerender] ${shellPath} not found — run \`vite build\` first.`);
    process.exit(1);
  }
  const shell = fs.readFileSync(shellPath, "utf-8");
  const routes = getRoutesFromSitemap();

  // dist/public/index.html is about to be overwritten with prerendered
  // homepage content (for exact "/" requests, which Netlify serves as a
  // direct static-file match). But netlify.toml's and _redirects' SPA
  // catch-all ("/* -> /index.html status=200") also serves that SAME file
  // for every route with no matching static file (e.g. /admin, /dashboard,
  // /team-login) — those need the original EMPTY-root shell, not the
  // homepage's markup, or a non-prerendered route would render mismatched
  // content before hydration sorts it out. Save the pre-prerender shell
  // under a separate name and point the catch-all at that instead (see
  // netlify.toml / client/public/_redirects).
  fs.writeFileSync(path.join(distDir, "200.html"), shell, "utf-8");

  // Middleware-mode Vite dev server: reuses vite.config.ts (aliases, env,
  // plugins) purely as an SSR module loader — nothing here binds a port.
  const vite: ViteDevServer = await createServer({
    configFile: path.join(root, "vite.config.ts"),
    server: { middlewareMode: true },
    appType: "custom",
  });

  let renderRoute: (routePath: string) => string;
  try {
    const entry = await vite.ssrLoadModule("/src/entry-server.tsx");
    renderRoute = entry.render;
  } catch (e) {
    await vite.close();
    console.error("[prerender] failed to load entry-server.tsx:", e);
    process.exit(1);
  }

  const failures: { route: string; error: string }[] = [];
  let done = 0;
  const start = Date.now();

  for (const routePath of routes) {
    try {
      const appHtml = renderRoute(routePath);
      let html = shell.replace('<div id="root"></div>', `<div id="root">${appHtml}</div>`);
      html = injectMeta(html, routePath);
      const outFile = outPathFor(routePath);
      fs.mkdirSync(path.dirname(outFile), { recursive: true });
      fs.writeFileSync(outFile, html, "utf-8");
      done++;
    } catch (e) {
      failures.push({ route: routePath, error: e instanceof Error ? e.stack ?? e.message : String(e) });
    }
  }

  await vite.close();

  const seconds = ((Date.now() - start) / 1000).toFixed(1);
  console.log(`[prerender] ${done}/${routes.length} routes rendered in ${seconds}s`);

  if (failures.length > 0) {
    console.error(`[prerender] ${failures.length} route(s) FAILED to prerender:`);
    for (const f of failures) {
      console.error(`\n── ${f.route} ──\n${f.error}`);
    }
    process.exit(1);
  }
}

main();
